### ISSUE TITLE
JSX, typescript, and jquery

### ISSUE THREAD

**Issue by epaulson** [ektrah/rdf-toolkit#8]
I am a bit confused on something - I'm not saying that you should use jQuery, but let's say there was a good reason to do so. Just as a test, I cloned the repo and ran 'npm install jquery', and then I added this to packages/explorer-site/src/main.ts - which right now is the a window click handler:

```javascript
window.onclick = function (ev) {
    let target = ev.target;
    while (target instanceof Element) {
        if (target.tagName === "A") {
            const href = target.getAttribute("data-href");
            const rel = target.getAttribute("rel");
            if (!rel) {
                ev.preventDefault();
                if (href) {
                    window.location.href = href;
                }
            }
            break;
        }
        target = target.parentElement;
    }
}

$(function(){
      alert("Hello from jquery!"); 
    });
```

This doesn't work - the compiler complains:
```
> @rdf-toolkit/explorer-site@0.1.0 prebuild
> tsc --noEmit

src/main.ts:19:1 - error TS2581: Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i --save-dev @types/jquery`.

19 $(function(){
```
So I took its suggestion of adding the types and ran npm install as it suggets, but then all heck broke loose:

```
> @rdf-toolkit/schema@0.1.0 build
> tsc --build


> @rdf-toolkit/explorer-shared@0.1.0 build
> tsc --noEmit

../../node_modules/@types/jquery/JQuery.d.ts:5:29 - error TS2552: Cannot find name 'HTMLElement'. Did you mean 'TElement'?

5 interface JQuery<TElement = HTMLElement> extends Iterable<TElement> {
                              ~~~~~~~~~~~

../../node_modules/@types/jquery/JQuery.d.ts:85:45 - error TS2304: Cannot find name 'Element'.

85     add(selector: JQuery.Selector, context: Element): this;
                                               ~~~~~~~

../../node_modules/@types/jquery/JQuery.d.ts:230:80 - error TS2304: Cannot find name 'Element'.

230     add(selector_elements_html_selection: JQuery.Selector | JQuery.TypeOrArray<Element> | JQuery.htmlString | JQuery | JQuery.Node): this;
                                                                                   ~~~~~~~

../../node_modules/@types/jquery/JQuery.d.ts:534:34 - error TS2304: Cannot find name 'Document'.
```
(lots more not included) 

There are a lot of types in explorer-views/src/jsx/ - was that you building out some minimal subset of what types you needed for the little bits of JSX you're using? Are there other libraries for those you'd consider using that might be more jquery-friendly?

This might not matter if jquery never gets added, but I was just wondering about how the code in explorer-views relates to the bigger picture.

**Comment by ektrah** [comment]
I'm not sure what's going wrong here. When you add a dependency on JQuery to the `packages/explorer-site` package ...

```bash
$ npm install --save jquery -w packages\explorer-site
$ npm install --save-dev @types/jquery -w packages\explorer-site
```

... and then compile the (completely unrelated) `packages/explorer-shared` package ...

```bash
$ npm run build -w packages\explorer-shared
```

... you get all these error messages.

These errors come from the fact that JQuery assumes a browser context by default, but the `packages/explorer-shared` package (correctly) doesn't have access to the DOM since the code is supposed to run in a Web Worker.

What I don't understand is why the errors appear in a package that doesn't have JQuery added at all. Maybe TypeScript has trouble with multiple packages in one repo here?

`explorer-views/src/jsx/` indeed contains a minimal implementation of a JSX runtime. What is needed is a JSX runtime that doesn't build a DOM structure, but compiles a string that can then be saved as an HTML file. I suppose this could also be achieved with React's [`renderToStaticMarkup`](https://react.dev/reference/react-dom/server/renderToStaticMarkup), but I don't know enough about React for that.

The types in `explorer-views/src/jsx/` are completely unrelated to the types in the JQuery error messages.

In general I don't think I would want to have a dependency on JQuery as it's pretty dated. The most popular frameworks these days seem to be Angular, React, Vue.js, etc.
